-- SECTION 1: DATASET & TABLE INSPECTION
-- Description:
-- Displays the records from each project table to
-- understand and validate the available dataset.
select * from products;
select * from orders;
select * from customers;
select * from categories;
select * from salespersons;

-- QUERY: PRODUCT ORDER DETAILS
-- =====================================================
-- Description:
-- Retrieves product names along with the dates on which
-- the products were ordered by joining the Products
-- and Orders tables using ProductID.
select p.productname , o.orderdate
from products p
join orders o 
on p.ProductID = o.ProductID;

-- QUERY: CATEGORY AND ORDER DETAILS
-- =====================================================
-- Description:
-- Retrieves the category name associated with each order
-- by joining the Orders, Products, and Categories tables.
select c.categoryname, o.orderid
from orders o
join products p
on o.productID = p.productiD
join categories c
on c.CategoryID = p.CategoryID;

-- SECTION 3: BASIC SALES ANALYSIS
-- =====================================================

-- QUERY 1: TOTAL SALES
-- Description:
-- Calculates the total sales amount across all orders.
select sum(salesamount) as Total_sales from orders;

-- QUERY 2: TOTAL NUMBER OF ORDERS
-- Description:
-- Counts the total number of orders in the dataset.
select count(*) as Total_orders from orders;

-- QUERY 3: TOTAL QUANTITY SOLD
-- Description:
-- Calculates the total quantity of products sold across
-- all orders.
select sum(quantity) as Total_quantity from orders;

-- QUERY 4: AVERAGE ORDER VALUE
-- Description:
-- Calculates the average sales amount per order.
select avg(salesamount) as average_amount_per_order from orders;

-- QUERY 5: HIGHEST ORDER VALUE
-- Description:
-- Identifies the highest sales amount recorded for
-- a single order.
select max(salesamount) as highest_order_amount from orders;

-- QUERY 6: LOWEST ORDER VALUE
-- Description:
-- Identifies the lowest sales amount recorded for
-- a single order.
select min(salesamount) as lowest_order_amount from orders;

-- QUERY 7: TOTAL SALES BY CUSTOMER
-- Description:
-- Calculates the total sales generated by each customer.
select customerid, sum(salesamount) as Total_sales from orders group by customerid;

-- QUERY 8: TOP 5 CUSTOMERS BY SALES
-- =====================================================
-- Description:
-- Identifies the top 5 customers based on their
-- total sales amount.
select Customerid, sum(salesamount) as total_sales
from orders
group by Customerid
order by total_sales desc
limit 5;

-- QUERY 9: TOP 5 PRODUCTS BY SALES
-- =====================================================
-- Description:
-- Identifies the top 5 products based on their
-- total sales amount by joining Products and Orders.

select p.productname, sum(o.salesamount) as total_sales
from products p
join orders o
on o.ProductID = p.productid
group by p.ProductName
order by total_sales desc
limit 5;

-- QUERY 10: TOTAL SALES BY CATEGORY
-- =====================================================
-- Description:
-- Calculates total sales for each product category
-- by joining Categories, Products, and Orders.
select c.categoryname, sum(o.salesamount) as total_sales
from categories c
join products p
on c.CategoryID = p.categoryID
join orders o
on o.productid = p.productid
group by CategoryName;

-- QUERY 11: TOP 5 SALESPERSONS BY SALES
-- =====================================================
-- Description:
-- Identifies the top 5 salespersons based on their
-- total sales generated from customer orders.
select s.salespersonid, sum(o.salesamount) as total_sales
from salespersons s
join orders o
on o.SalespersonID = s.SalespersonID
group by SalespersonID
order by total_sales desc
limit 5;

-- QUERY 12: TOP 3 CITIES BY SALES
-- =====================================================
-- Description:
-- Identifies the top 3 cities based on total sales
-- by joining Customers and Orders.
select c.city as cityname, sum(o.salesamount) as total_sales
from customers c
join orders o
on c.CustomerID = o.CustomerID
group by cityname
order by total_sales desc
limit 3;

-- QUERY 13: SALES BY CUSTOMER SEGMENT
-- =====================================================
-- Description:
-- Calculates total sales for each customer segment
-- by joining Customers and Orders.
select c.customersegment, sum(o.salesamount) as total_sales
from customers c
join orders o
on o.customerid = c.CustomerID
group by c.CustomerSegment
order by total_sales desc;

-- QUERY 14: MONTHLY SALES TREND
-- =====================================================
-- Description:
-- Calculates total sales for each month and year
-- to analyze sales trends over time.
select year(orderdate) as year_order, month(orderdate) as month_order , sum(SalesAmount) as total_sales
from orders
group by year(OrderDate), month(OrderDate)
order by year_order,month_order;

-- QUERY 15: MONTHLY ORDER COUNT
-- =====================================================
-- Description:
-- Calculates the total number of orders placed in
-- each month to analyze monthly order volume.
select count(orderid) , month(orderdate) as month_order
from orders
group by month(orderdate)
order by month_order;

-- QUERY 16: AVERAGE ORDER VALUE BY MONTH
-- =====================================================
-- Description:
-- Calculates the average sales amount per order for
-- each month and year to analyze changes in order value.
SELECT
    YEAR(OrderDate) AS order_year,
    MONTH(OrderDate) AS order_month,
    AVG(SalesAmount) AS average_order_value
FROM orders
GROUP BY YEAR(OrderDate), MONTH(OrderDate)
ORDER BY order_year, order_month;

-- QUERY 17: TOTAL SALES BY REGION
-- =====================================================
-- Description:
-- Calculates total sales generated in each region by
-- joining Orders with Salespersons and grouping the
-- results by region.
select s.region, sum(o.salesamount) as total_sales
from orders o
join salespersons s
on o.SalespersonID = s.SalespersonID
group by s.region
order by total_sales desc;

-- QUERY 18: SALES BY CATEGORY AND REGION
-- =====================================================
-- Description:
-- Calculates total sales for each product category
-- across different regions by joining Orders, Products,
-- Categories, and Salespersons.
select sum(o.salesamount) as total_sales, c.categoryname, s.region 
from  orders o
join products p
on o.productid = p.productid
join categories c
on p.CategoryID = c.categoryid
join salespersons s
on o.salespersonid = s.SalespersonID
group by c.categoryname, s.region
order by s.region desc;

-- QUERY 19: TOP-SELLING CATEGORY BY REGION
-- =====================================================
-- Description:
-- Ranks product categories within each region based on
-- total sales and identifies the highest-selling category
-- in every region using the RANK() window function.
with category_rank as(
select c.categoryname, s.region, sum(o.salesamount) as total_sales,
 rank()
 over( partition by s.region
 order by sum(o.SalesAmount) desc) as category_rank
 from orders o
 join products p
 on p.ProductID = o.ProductID
 join categories c
 on c.CategoryID = p.CategoryID
 join salespersons s
 on s.SalespersonID = o.SalespersonID
 group by c.categoryname, s.region)
 select categoryname,region, total_sales
 from category_rank
 where category_rank = 1;
 
 -- QUERY 20: TOP CUSTOMER BY CITY
-- =====================================================
-- Description:
-- Ranks customers within each city based on their
-- total purchase amount and identifies the highest-
-- spending customer in every city using RANK().
 with customer_rank as(
 select c.customername, sum(o.salesamount) as highest_purchase, c.city,
 rank() over( partition by c.city order by sum(o.salesamount) desc )as customer_rank
 from orders o
 join customers c
on o.CustomerID = c.CustomerID
group by c.city,c.customername)
select customername,highest_purchase,city
from customer_rank
where customer_rank = 1;

-- QUERY 21: CUSTOMERS AND THEIR ORDERS
-- =====================================================
-- Description:
-- Retrieves all customers along with their order IDs.
-- A LEFT JOIN ensures that customers with no orders
-- are also included in the result.
select c.customername,c.customerid, O.ORDERID
from customers c
left join orders o
on o.customerid = c.customerid;

-- QUERY 22: CUSTOMERS WITH MORE THAN 3 ORDERS
-- =====================================================
-- Description:
-- Identifies customers who have placed more than
-- 3 orders and ranks them by their total order count.
SELECT C.CUSTOMERNAME, COUNT(O.ORDERID) AS MORETHAN_3_ORDERS
FROM ORDERS O
JOIN CUSTOMERS C 
ON O.CUSTOMERID = C.CUSTOMERID
group by C.CUSTOMERNAME
HAVING count( O.ORDERID) > 3
order by MORETHAN_3_ORDERS
DESC ;

-- QUERY 23: HIGH-VALUE CUSTOMERS
-- =====================================================
-- Description:
-- Identifies customers whose total sales exceed 20,000
-- and ranks them by their total purchase amount.
SELECT C.CUSTOMERID ,C.CUSTOMERNAME, SUM(O.SALESAMOUNT) AS TOTAL_SALES
FROM orders O
JOIN CUSTOMERS C
ON C.CUSTOMERID = O.CUSTOMERID
group by C.CUSTOMERID, C.CUSTOMERNAME
HAVING TOTAL_SALES > 20000
order by TOTAL_SALES DESC;

-- QUERY 24: MONTHLY SALES RANKING
-- =====================================================
-- Description:
-- Calculates total sales for each month and ranks
-- the months from highest to lowest sales performance.
SELECT MONTH(ORDERDATE), SUM(SALESAMOUNT) AS TOTAL_SALES
FROM ORDERS 
group by MONTH(ORDERDATE)
ORDER BY total_sales DESC;

-- QUERY 25: SALES BY DAY OF WEEK
-- =====================================================
-- Description:
-- Calculates total sales for each day of the week
-- and ranks the days from highest to lowest sales.
select dayname(orderdate),sum(salesamount) as highest_sales
from orders
group by dayname(OrderDate)
order by highest_sales 
desc;

-- QUERY 26: AVERAGE ORDER VALUE BY CUSTOMER SEGMENT
-- =====================================================
-- Description:
-- Calculates the average sales amount per order for
-- each customer segment and ranks the segments by
-- average order value.
select c.customersegment, avg(o.salesamount) as average_amount
from orders o
join customers c 
on c.CustomerID = o.CustomerID
group by c.CustomerSegment
order by average_amount desc;

-- QUERY 27: AVERAGE ORDER VALUE BY DISCOUNT STATUS
-- =====================================================
-- Description:
-- Compares the average sales amount for orders with
-- discounts versus orders without discounts.
select 
case when discountpct > 0 then 'discounted'
else  'not_discounted' end as discount_status,
avg(salesamount) from orders
group by discount_status
order by avg(salesamount) desc;

-- QUERY 28: AVERAGE SALES BY SALESPERSON EXPERIENCE
-- =====================================================
-- Description:
-- Compares the average sales amount generated by
-- experienced and less-experienced salespersons based
-- on their years of experience.
select 
case when ExperienceYears > 5 then ' experienced'
else 'less experience' end as work_experience,avg(Salesamount) AS TOTAL_sales
from orders o
join salespersons s
on s.SalespersonID = o.SalespersonID
group by work_experience
order by TOTAL_sales ;

-- QUERY 29: TOTAL SALES BY SALESPERSON EXPERIENCE
-- =====================================================
-- Description:
-- Compares total sales generated by well-experienced
-- and less-experienced salespersons based on their
-- years of experience.
select 
case when experienceyears > 5 then 'well expirenced'
else 'less expirenced' end as experience_type, sum(salesamount) as total_sales
from orders o
join salespersons s
on o.SalespersonID = s. SalespersonID
group by experience_type
order by total_sales desc;

-- QUERY 30: SALESPERSON PERFORMANCE BY SALES AND ORDERS
-- =====================================================
-- Description:
-- Calculates total sales and total orders for each
-- salesperson and ranks salespersons primarily by
-- total sales and secondarily by order count.
select salespersonname, sum(salesamount) as total_sales,count(OrderID) as total_orders
from orders o
join salespersons s
on s.SalespersonID = o.SalespersonID
group by salespersonname
order by total_sales desc,total_orders desc;

-- QUERY 31: SALESPERSON WITH HIGHEST AVERAGE ORDER VALUE
-- =====================================================
-- Description:
-- Identifies the salesperson with the highest average
-- sales amount per order.
select salespersonname, avg(salesamount) as highest_order_value
from orders o
join salespersons s
on s.SalespersonID = o.SalespersonID
group by SalespersonName
order by highest_order_value desc
limit 1;

-- QUERY 32: TOP SALESPERSON BY REGION
-- =====================================================
-- Description:
-- Ranks salespersons within each region based on their
-- total sales and identifies the top salesperson in
-- every region using the RANK() window function.
 WITH Category_rank as (
 select
 s.salespersonname,
 s.region,
 sum(o.salesamount) as total_sales,
 rank() over( partition by s.region 
 order by sum(o.salesamount) desc) as Category_rank
 from orders o
 JOIN salespersons s
 on o.salespersonid = s.salespersonid
 group by s.SalespersonName, s.Region
 order by total_sales)
 select salespersonname, region, total_sales
 from category_rank
 where category_rank = 1;
 
 -- QUERY 33: CUSTOMERS ABOVE AVERAGE SPENDING
-- =====================================================
-- Description:
-- Identifies customers whose total sales are higher
-- than the average total sales across all customers.
-- Uses a nested subquery to calculate the average
-- customer spending.
 select c.customerid, sum(o.salesamount) as total_sales
 from orders o 
 join customers c
 on c.customerid = o.CustomerID
 group by CustomerID 
 having sum(o.salesamount) >
 (select avg(customer_total) from
 (select CustomerID, sum(SalesAmount) as customer_total
 from orders
 group by CustomerID )
 as customer_sales
 )
 order by total_sales desc;
 
 -- QUERY 34: SALESPERSON RANKING USING ROW_NUMBER()
-- =====================================================
-- Description:
-- Calculates total sales for each salesperson and assigns
-- a unique sales ranking using the ROW_NUMBER() window
-- function, with the highest-selling salesperson ranked first.
 select s.salespersonid, s.salespersonname, sum(o.salesamount) as total_sales,
 Row_number() over(
 order by sum(o.salesamount) desc) as sales_rank
 from orders o
 join salespersons s
on o.SalespersonID = s.SalespersonID
group by s.SalespersonID,s.SalespersonName; 

-- QUERY 35: SALESPERSON RANKING USING DENSE_RANK()
-- =====================================================
-- Description:
-- Calculates total sales for each salesperson and assigns
-- a ranking using DENSE_RANK(), allowing tied salespersons
-- to share the same rank without gaps in the ranking.
select s.salespersonid, s.salespersonname, sum(o.salesamount) as total_sales,
dense_rank() OVER(
order by SUM(O.SALESAMOUNT) DESC) AS SALES_RANK
FROM ORDERS O
JOIN salespersons s
ON S.SALESPERSONID = O.SALESPERSONID
group by S.SalespersonID, S.SalespersonName;

-- QUERY 36: TOP 3 SALESPERSONS USING DENSE_RANK()
-- =====================================================
-- Description:
-- Ranks salespersons by total sales using DENSE_RANK()
-- and returns all salespersons within the top 3 ranks.
-- Tied salespersons receive the same rank.
WITH SALESPERSON_RANK AS ( 
SELECT S.SALESPERSONID, S.SALESPERSONNAME, SUM(O.SALESAMOUNT) AS TOTAL_SALES,
dense_rank () OVER(
order by SUM(O.SALESAMOUNT) DESC) AS SALES_RANK
FROM ORDERS O
JOIN salespersons S
ON S.SalespersonID = O.SALESPERSONID
group by S.SalespersonID, S.SalespersonName)
SELECT SALESPERSONID, SALESPERSONNAME, TOTAL_SALES, SALES_RANK
FROM SALESPERSON_RANK
WHERE SALES_RANK <= 3;

-- QUERY 37: TOP-SELLING PRODUCT IN EACH CATEGORY
-- =====================================================
-- Description:
-- Ranks products within each category based on total
-- sales and identifies the highest-selling product in
-- every category using DENSE_RANK().
WITH PRODUCTS_RANKING AS(
SELECT P.PRODUCTNAME, C.CATEGORYNAME , SUM(O.SALESAMOUNT) AS TOTAL_SALES , dense_rank()
OVER(partition by C.CategoryName ORDER BY  SUM(O.SALESAMOUNT) DESC) AS P_RANKING	
FROM ORDERS O
JOIN PRODUCTS p
ON O.PRODUCTID = P.PRODUCTID
JOIN categories C
ON P.CATEGORYID = C.CategoryID
group by P.PRODUCTNAME,C.CategoryName)
SELECT PRODUCTNAME, CATEGORYNAME ,TOTAL_SALES, P_RANKING
FROM PRODUCTS_RANKING
WHERE P_RANKING = 1
order by TOTAL_SALES;

-- QUERY 38: TOP CUSTOMER IN EACH CUSTOMER SEGMENT
-- =====================================================
-- Description:
-- Ranks customers within each customer segment based
-- on total sales and identifies the highest-spending
-- customer in every segment using DENSE_RANK().
WITH CUSTOMER_SEGMENT_RANKING AS(
SELECT C.CUSTOMERNAME, C.CUSTOMERSEGMENT, SUM(O.SALESAMOUNT) AS TOTAL_SALES, dense_rank()OVER(partition by C.CUSTOMERSEGMENT
order by SUM(O.SALESAMOUNT) DESC) AS CATEGORY_RANKING
FROM ORDERS o
JOIN CUSTOMERS C
ON O.CUSTOMERID = C.CUSTOMERID
group by C.CUSTOMERNAME,C.CUSTOMERSEGMENT)
select CUSTOMERNAME, CUSTOMERSEGMENT ,TOTAL_SALES
FROM CUSTOMER_SEGMENT_RANKING 
WHERE CATEGORY_RANKING = 1
order by TOTAL_SALES DESC;

-- QUERY 39: CATEGORY SALES CONTRIBUTION PERCENTAGE
-- =====================================================
-- Description:
-- Calculates total sales for each product category and
-- determines each category's percentage contribution
-- to the overall sales.
select c.categoryname, sum(o.salesamount), round(sum(o.salesamount)/(select sum(salesamount)from orders) * 100,2) as percentage
from orders o
join products p
on p.ProductID = o.ProductID
join categories c
on p.CategoryID = c.CategoryID
group by c.CategoryName,c.CategoryID;

-- QUERY 40: SALESPERSON SALES CONTRIBUTION PERCENTAGE
-- =====================================================
-- Description:
-- Calculates total sales for each salesperson and
-- determines each salesperson's percentage contribution
-- to the overall company sales.
select s.salespersonname, sum(o.salesamount) as total_sales,round(sum(o.salesamount)/(select sum(salesamount) from orders )*100, 2 ) as percentage
from orders o
join salespersons s
on o.SalespersonID = s.SalespersonID
group by s.SalespersonName, s.SalespersonID;

-- QUERY 41: MONTHLY SALES GROWTH ANALYSIS
-- =====================================================
-- Description:
-- Calculates total sales for each year and month,
-- compares current month sales with the previous month,
-- and calculates the month-over-month sales difference.
with sales_growth as
(select year(orderdate) as year_date,
month(orderdate) as month_date,sum(salesamount) as total_sales
from orders
group by year_date, month_date)
select year_date, month_date, total_sales, 
lag(total_sales) over(order by year_date,month_date) as previous_month_sales,
total_sales - lag(total_sales) over(order by year_date,month_date) as difference
from sales_growth
order by year_date, month_date;

-- QUERY 42: MONTHLY SALES GROWTH PERCENTAGE
-- =====================================================
-- Description:
-- Calculates total sales for each year and month,
-- compares current month sales with the previous month,
-- and calculates the month-over-month sales growth
-- percentage.
WITH sales_growth AS (
    SELECT
        YEAR(OrderDate) AS year_date,
        MONTH(OrderDate) AS month_date,
        SUM(SalesAmount) AS total_sales
    FROM orders
    GROUP BY year_date, month_date
)
SELECT
    year_date,
    month_date,
    total_sales,
    LAG(total_sales) OVER (ORDER BY year_date, month_date) AS previous_month_sales,
    ROUND((total_sales - LAG(total_sales) OVER (
            ORDER BY year_date, month_date))
        / LAG(total_sales) OVER (
            ORDER BY year_date, month_date
        ) * 100,
        2
    ) AS growth_percentage
FROM sales_growth
ORDER BY month_date;

-- QUERY 43: TOP-SELLING CATEGORY BY MONTH
-- =====================================================
-- Description:
-- Calculates total sales for each product category
-- and ranks the categories within each month and year.
-- Identifies the highest-selling category for each month.
with category_ranking as (
select MONTH(O.ORDERDATE) AS MONTH_DATE,
YEAR(O.ORDERDATE) AS YEAR_DATE,
 c.categoryname, 
 SUM(O.SALESAMOUNT) AS TOTAL_SALES,
       RANK()OVER (partition by MONTH(O.ORDERDATE),YEAR(O.ORDERDATE) 
       order by SUM(O.SALESAMOUNT) DESC) AS CATEGORY_RANK
       FROM ORDERS o
       JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID
JOIN CATEGORIES C
ON P.CATEGORYID = C.CATEGORYID
group by c.categoryname,month(o.orderdate),year(o.orderdate))
SELECT CATEGORYNAME, MONTH_date, YEAR_date, total_sales
FROM CATEGORY_RANKING 
WHERE CATEGORY_RANK = 1
order by year_date, month_date;

-- QUERY 44: HIGHEST-SELLING PRODUCT
-- =====================================================
-- Description:
-- Calculates total sales for each product,
-- ranks products based on total sales,
-- and identifies the highest-selling product.
SELECT
    p.ProductID,
    p.ProductName,
    SUM(o.SalesAmount) AS total_sales
FROM products p
JOIN orders o
    ON p.ProductID = o.ProductID
GROUP BY p.ProductID, p.ProductName
ORDER BY total_sales DESC
LIMIT 1;

-- QUERY 45: LOWEST-SELLING PRODUCT
-- =====================================================
-- Description:
-- Calculates total sales for each product,
-- ranks products based on total sales,
-- and identifies the lowest-selling product.
SELECT
    p.ProductID,
    p.ProductName,
    SUM(o.SalesAmount) AS total_sales
FROM products p
JOIN orders o
    ON p.ProductID = o.ProductID
GROUP BY p.ProductID, p.ProductName
ORDER BY total_sales ASC
LIMIT 1;

-- QUERY 46: HIGHEST-SELLING CATEGORY
-- =====================================================
-- Description:
-- Calculates total sales for each product category,
-- ranks categories based on total sales,
-- and identifies the highest-selling category.
SELECT
    c.CategoryID,
    c.CategoryName,
    SUM(o.SalesAmount) AS total_sales
FROM orders o
JOIN products p
    ON o.ProductID = p.ProductID
JOIN categories c
    ON p.CategoryID = c.CategoryID
GROUP BY c.CategoryID, c.CategoryName
ORDER BY total_sales DESC
LIMIT 1;

-- QUERY 47: SALESPERSON WITH HIGHEST NUMBER OF ORDERS
-- =====================================================
-- Description:
-- Calculates the total number of orders handled by each
-- salesperson and identifies the salesperson with the
-- highest number of orders.
SELECT
    s.SalespersonID,
    s.SalespersonName,
    COUNT(o.OrderID) AS total_orders
FROM orders o
JOIN salespersons s
    ON o.SalespersonID = s.SalespersonID
GROUP BY s.SalespersonID, s.SalespersonName
ORDER BY total_orders DESC
LIMIT 1;

-- QUERY 48: SALESPERSONS ABOVE REGIONAL AVERAGE SALES
-- =====================================================
-- Description:
-- Calculates total sales for each salesperson,
-- compares each salesperson's sales with the average
-- sales of their respective region,
-- and identifies salespersons performing above
-- their regional average.
WITH salesperson_sales AS (
    SELECT
        s.SalespersonID,
        s.SalespersonName,
        s.Region,
        SUM(o.SalesAmount) AS total_sales
    FROM salespersons s
    JOIN orders o
        ON s.SalespersonID = o.SalespersonID
    GROUP BY
        s.SalespersonID,
        s.SalespersonName,
        s.Region
)
SELECT
    SalespersonID,
    SalespersonName,
    Region,
    total_sales
FROM salesperson_sales ss
WHERE total_sales > (
    SELECT AVG(ss2.total_sales)
    FROM salesperson_sales ss2
    WHERE ss2.Region = ss.Region
)
ORDER BY Region, total_sales DESC;

-- QUERY 49: PRODUCTS ABOVE CATEGORY AVERAGE SALES
-- =====================================================
-- Description:
-- Calculates total sales for each product within its
-- category, compares each product's sales with the
-- average sales of its category, and identifies products
-- performing above their category average.
WITH PRODUCT_RANKING AS (
SELECT P.PRODUCTNAME, SUM(O.SALESAMOUNT) AS TOTAL_SALES, C.CATEGORYNAME
FROM ORDERS O
JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID
JOIN CATEGORIES C
ON P.CATEGORYID = C.CATEGORYID
group by P.PRODUCTNAME, C.CATEGORYNAME)
SELECT PRODUCTNAME , CATEGORYNAME, TOTAL_SALES
FROM PRODUCT_RANKING PR
WHERE TOTAL_SALES > (SELECT AVG(PR2.TOTAL_SALES)
FROM PRODUCT_RANKING PR2
WHERE PR.CATEGORYNAME = PR2.CATEGORYNAME)
order by CATEGORYNAME, TOTAL_SALES DESC;

-- QUERY 50: MONTHLY RUNNING TOTAL SALES
-- =====================================================
-- Description:
-- Calculates total sales for each month and year,
-- and calculates the cumulative running total of sales
-- over time.
WITH monthly_sales AS (
    SELECT
        YEAR(OrderDate) AS year_date,
        MONTH(OrderDate) AS month_date,
        SUM(SalesAmount) AS total_sales
    FROM orders
    GROUP BY YEAR(OrderDate), MONTH(OrderDate)
)
SELECT
    year_date,
    month_date,
    total_sales,
    SUM(total_sales) OVER (
        ORDER BY year_date, month_date
    ) AS running_total
FROM monthly_sales
ORDER BY year_date, month_date;

-- QUERY 51: HIGHEST MONTH-OVER-MONTH SALES GROWTH
-- =====================================================
-- Description:
-- Calculates monthly sales growth compared with the
-- previous month and identifies the month with the
-- highest sales growth percentage.
WITH monthly_sales AS (
    SELECT
        YEAR(OrderDate) AS year_date,
        MONTH(OrderDate) AS month_date,
        SUM(SalesAmount) AS total_sales
    FROM orders
    GROUP BY YEAR(OrderDate), MONTH(OrderDate)
),
growth AS (
    SELECT
        year_date,
        month_date,
        total_sales,
        LAG(total_sales) OVER (
            ORDER BY year_date, month_date
        ) AS previous_sales
    FROM monthly_sales
)
SELECT
    year_date,
    month_date,
    ROUND(
        (total_sales - previous_sales) / previous_sales * 100,
        2
    ) AS growth_percentage
FROM growth
WHERE previous_sales IS NOT NULL
ORDER BY growth_percentage DESC
LIMIT 1;

-- QUERY 52: CATEGORY SALES CONTRIBUTION BY REGION
-- =====================================================
-- Description:
-- Calculates total sales for each category within each
-- region and determines each category's percentage
-- contribution to the overall sales of that region.
WITH region_category_sales AS (
    SELECT
        s.Region,
        c.CategoryName,
        SUM(o.SalesAmount) AS category_sales
    FROM orders o
    JOIN salespersons s
        ON o.SalespersonID = s.SalespersonID
    JOIN products p
        ON o.ProductID = p.ProductID
    JOIN categories c
        ON p.CategoryID = c.CategoryID
    GROUP BY s.Region, c.CategoryID, c.CategoryName
)
SELECT
    Region,
    CategoryName,
    category_sales,
    ROUND(
        category_sales /
        SUM(category_sales) OVER (PARTITION BY Region) * 100,
        2
    ) AS percentage_of_region_sales
FROM region_category_sales
ORDER BY Region, percentage_of_region_sales DESC;

-- QUERY 53: TOP CUSTOMER BY REGION
-- =====================================================
-- Description:
-- Calculates total sales for each customer within
-- each region, ranks customers based on their sales,
-- and identifies the highest-selling customer in
-- each region.
WITH customer_region_sales AS (
    SELECT
        s.Region,
        c.CustomerID,
        c.CustomerName,
        SUM(o.SalesAmount) AS total_sales
    FROM orders o
    JOIN customers c
        ON o.CustomerID = c.CustomerID
    JOIN salespersons s
        ON o.SalespersonID = s.SalespersonID
    GROUP BY
        s.Region,
        c.CustomerID,
        c.CustomerName
),
ranked_customers AS (
    SELECT
        Region,
        CustomerID,
        CustomerName,
        total_sales,
        DENSE_RANK() OVER (
            PARTITION BY Region
            ORDER BY total_sales DESC
        ) AS customer_rank
    FROM customer_region_sales
)
SELECT
    Region,
    CustomerID,
    CustomerName,
    total_sales
FROM ranked_customers
WHERE customer_rank = 1
ORDER BY Region;

-- QUERY 54: HIGHEST-SELLING MONTH
-- =====================================================
-- Description:
-- Calculates total sales for each month and year,
-- ranks the months based on total sales,
-- and identifies the month with the highest sales.
SELECT
    YEAR(OrderDate) AS order_year,
    MONTH(OrderDate) AS order_month,
    SUM(SalesAmount) AS total_sales
FROM orders
GROUP BY YEAR(OrderDate), MONTH(OrderDate)
ORDER BY total_sales DESC
LIMIT 1;

-- QUERY 55: HIGHEST CATEGORY SALES CONTRIBUTION
-- =====================================================
-- Description:
-- Calculates total sales for each product category,
-- determines each category's percentage contribution
-- to overall company sales,
-- and identifies the category with the highest
-- sales contribution percentage.
SELECT
    c.CategoryName,
    SUM(o.SalesAmount) AS category_sales,
    ROUND(
        SUM(o.SalesAmount) /
        (SELECT SUM(SalesAmount) FROM orders) * 100,
        2
    ) AS percentage
FROM orders o
JOIN products p
    ON p.ProductID = o.ProductID
JOIN categories c
    ON p.CategoryID = c.CategoryID
GROUP BY c.CategoryID, c.CategoryName
ORDER BY percentage DESC
LIMIT 1;

-- QUERY 56: MONTHLY SALES GROWTH PERCENTAGE
-- =====================================================
-- Description:
-- Calculates total sales for each year and month,
-- compares current month sales with the previous month,
-- and calculates the month-over-month sales growth
-- percentage.
WITH sales_growth AS (
    SELECT
        YEAR(OrderDate) AS year_date,
        MONTH(OrderDate) AS month_date,
        SUM(SalesAmount) AS total_sales
    FROM orders
    GROUP BY year_date, month_date
)
SELECT
    year_date,
    month_date,
    total_sales,
    LAG(total_sales) OVER (
        ORDER BY year_date, month_date
    ) AS previous_month_sales,
    ROUND(
        (total_sales - LAG(total_sales) OVER (
            ORDER BY year_date, month_date
        ))
        / LAG(total_sales) OVER (
            ORDER BY year_date, month_date
        ) * 100,
        2
    ) AS growth_percentage
FROM sales_growth
ORDER BY year_date, month_date;


